# Cloud Build configuration for automatic deployment
# Triggered on push to main branch

steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mindscout-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mindscout-backend:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mindscout-backend:$COMMIT_SHA'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mindscout-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mindscout-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID'
      - '--set-secrets'
      - 'ANTHROPIC_API_KEY=anthropic-api-key:latest,DATABASE_URL=database-url:latest,SECRET_KEY=secret-key:latest'
      - '--add-cloudsql-instances'
      - '${_INSTANCE_CONNECTION_NAME}'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--port'
      - '8080'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

# Store the built images
images:
  - 'gcr.io/$PROJECT_ID/mindscout-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/mindscout-backend:latest'

# Substitutions (can be overridden)
substitutions:
  _INSTANCE_CONNECTION_NAME: '${PROJECT_ID}:us-central1:mindscout-db'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

# Timeout for the entire build
timeout: '1200s'
